FROM oven/bun

WORKDIR /app


COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./apps/backend/package.json ./apps/backend/package.json


COPY ./packages ./packages
COPY ./apps/backend ./apps/backend

RUN bun install


EXPOSE 3001

CMD ["bun", "run","--cwd", "apps/backend", "index.ts"]