FROM oven/bun

WORKDIR /app

# 1. Install unzip and all required Linux graphics/audio libraries for Puppeteer
RUN apt-get update && apt-get install -y \
    unzip \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgbm1 \
    libgcc1 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    lsb-release \
    wget \
    xdg-utils \
    && rm -rf /var/lib/apt/lists/*

# 2. Copy your dependency files
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./apps/backend/package.json ./apps/backend/package.json

# 3. Copy source code
COPY ./packages ./packages
COPY ./apps/backend ./apps/backend

# 4. Install Bun packages (Puppeteer will now successfully extract and configure Chrome)
RUN bun install

EXPOSE 3001

CMD ["bun", "run","--cwd", "apps/backend", "index.ts"]